#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Zend\Mvc\Application;
use Zend\Stdlib\ArrayUtils;

defined('STORAGE_PATH') || define(
    'STORAGE_PATH',
    realpath(dirname(__FILE__) . '/storage')
);

$appConfig = include __DIR__ . '/config/application.config.php';
if (file_exists(__DIR__ . '/config/development.config.php')) {
    $appConfig = ArrayUtils::merge(
        $appConfig,
        include __DIR__ . '/config/development.config.php'
    );
}

chdir(__DIR__);

$zfApp = Application::init($appConfig);

$application = new Symfony\Component\Console\Application('Babelium', '0.0.1');
$convertCommand = new ApiV3\Command\ConvertCommand($zfApp);
$responseConvertCommand = new ApiV3\Command\ResponseConvertCommand($zfApp);

$application->add($convertCommand);
$application->add($responseConvertCommand);

//$application->setDefaultCommand($convertCommand->getName(), true);

$application->run();
